name: BedWars
version: FleetHD
api: 3.0..0-ALPHA11
main: FleetHD\BedWars
author: FleetHD, traduced by GeoZDev
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Baslat:
        description: Bedwars Forcestart Command
